export type SettingsMotorEntity = {
    id: string,
    vehicleId: string,
    tractionControl: number,
    abs: number,
    esp: number,
    driftAssist: number,
    areoDistribution:  number,
    gearbox: number,
    tireGripFront: number,
    tireGripRear: number,
    brakePower: number,
    brakeBalance: number,
    suspCompFront: number,
    suspRebFront: number,
    suspCompRear: number,
    suspRebRear: number,
}

export type SettingsMotorReq = {
    vehicleId: string,
    tractionControl: number,
    abs: number,
    esp: number,
    driftAssist: number,
    areoDistribution:  number,
    gearbox: number,
    tireGripFront: number,
    tireGripRear: number,
    brakePower: number,
    brakeBalance: number,
    suspCompFront: number,
    suspRebFront: number,
    suspCompRear: number,
    suspRebRear: number,
}

export type SettingsMotorRes = {
    id?: string,
    vehicleId: string,
    tractionControl: number,
    abs: number,
    esp: number,
    driftAssist: number,
    areoDistribution:  number,
    gearbox: number,
    tireGripFront: number,
    tireGripRear: number,
    brakePower: number,
    brakeBalance: number,
    suspCompFront: number,
    suspRebFront: number,
    suspCompRear: number,
    suspRebRear: number,
}